// File: app/api/share/route.js

import { NextResponse } from 'next/server';
import nodemailer from 'nodemailer';

export async function POST(request) {
  try {
    const { recipients, summary } = await request.json();

    if (!recipients || !summary) {
      return NextResponse.json({ error: 'Recipients and summary are required.' }, { status: 400 });
    }

    // Configure the transporter for Nodemailer using Brevo's details
    const transporter = nodemailer.createTransport({
      host: process.env.EMAIL_HOST,
      port: process.env.EMAIL_PORT,
      secure: false, // true for 465, false for other ports
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS,
      },
    });

    // Set up email data
    const mailOptions = {
      from: `"Meeting Summarizer" <${process.env.EMAIL_USER}>`,
      to: recipients,
      subject: 'Your AI-Generated Meeting Summary',
      html: `
        <h1>Meeting Summary</h1>
        <pre style="white-space: pre-wrap; font-family: monospace; background-color: #f4f4f4; padding: 15px; border-radius: 5px;">${summary}</pre>
        <p>--<br>Generated by AI Meeting Summarizer</p>
      `,
    };

    // Send the email
    await transporter.sendMail(mailOptions);
    
    return NextResponse.json({ message: 'Email sent successfully!' });

  } catch (error) {
    console.error('Error sending email:', error);
    return NextResponse.json({ error: 'Failed to send email.' }, { status: 500 });
  }
}